# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ios Zen

############################################################################
# baseurl: the subpath of your site, e.g. /blog
#    must be changed to "" when merge gh-pages to master
#    branch of username.github.io
# url: the base hostname & protocol for your site
#    [ custom domain | username.github.io | blank ]
############################################################################
baseurl: "/ioszen.com-redesign"
url: ""


# Build settings
markdown: kramdown

# Google Analytics tracking ID
ga_tracking_id: ""
